### ISSUE TITLE
data table: titles ready for advice: i.e. F (ages1-2) per year

### ISSUE THREAD

**Issue by martinezinigo** [ices-tools-prod/icesSAG#37]
Also add:
* description of confidence intervals

might need feedback from ACOM

**Comment by slarge** [comment]
If I understand correctly, this issue is relevant to the Summary of the Assessment. It would be a huge time- saver for Advisory Staff if the table could be somewhat formatted in the .docx output. It doesn't have to be perfect, but the proper font, alignment, rows (e.g., everybody deletes the "average" row), and headers (not in bold) would be really beneficial.

**Comment by Milldaz** [comment]
We need to agree on a set of terms that we use consistently to describe confidence intervals (these can be confusing to recipients of advice so we need clear simple explanations that are fairly consistent across sheets). The average row should go.

I also agree it would be good to have it more standardised.  There will always be stocks that will still need some re-arranging (e.g. stocks with lots of custom columns, some of the Icelandic stocks with reference biomasses and HRs have a specific format they like etc.).

Where do I find the details for font/row, shading size etc.?

**Comment by slarge** [comment]
You can find that nitty gritty details [here](https://community.ices.dk/Advice/Advice2017/Advice%20documents/Secretariat%20Guidelines%20for%20Formatting%20Advice%202017.docx?Web=1)

**Comment by Milldaz** [comment]
CIs added. Updating of table headers to use this information to be done. Added to list of output updates required.
