### ISSUE TITLE
Catches missing for key = 8036

### ISSUE THREAD

**Issue by slarge** [ices-tools-prod/icesSAG#96]
https://standardgraphs.ices.dk/ViewSourceData.aspx?key=8036

There are no catches/landings/indices visible for this stock.

**Comment by Milldaz** [comment]
I think last year for eel all the catch data went into custom columns (because it is split by location).  Not sure where it is hiding on SAG.

A more general issue here is that when we click 'view source data', ALL the data uploaded should be shown (including custom columns). This doesn't happen at the moment.

**Comment by colinpmillar** [comment]
You can access the data via the download xml and then open in excel….  So it is there and accessible.  However I agree that the source data should show all data.  Will add an issue for that.

**Comment by colinpmillar** [comment]
this is a sub issue of #82 so closing this as duplicate
